AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  pdfFormFiller:
    Type: 'AWS::Serverless::Function'
    Properties:
      Description: ''
      Handler: index.handler
      MemorySize: 128
      Role: 'arn:aws:iam::815621908682:role/service-role/pdfFormFiller-role-0h9l9njq'
      Runtime: nodejs12.x
      Timeout: 300
